# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ariticle_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=5000, verbose_name='内容')),
                ('date', models.DateField(default='2019-01-02')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Users')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Article_tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
                ('article', models.ManyToManyField(null=True, to='personal.Article')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'article_tag',
            },
        ),
    ]
