# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ariticle_id',
            new_name='article_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default='2019-01-03'),
        ),
    ]
