# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-10 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20190110_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_del',
        ),
    ]
